services:
  engine:
    build: .
    container_name: engine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1323:1323"
    networks:
      - search_net
networks:
  search_net:
    external: true
