default: dev

# Variables
VERSION := "1.0.0"
BUILDTIME := `date -u '+%Y-%m-%d_%H:%M:%S'`
BIN := "spider"
ENTRY := "./cmd/spider/main.go"

# Flags
LDFLAGS := "-s -w -X main.Version={{VERSION}} -X main.BuildTime={{BUILDTIME}}"
GCFLAGS := "all=-B"

dev:
    go run {{ENTRY}}

build:
    go build -ldflags="{{LDFLAGS}}" -gcflags="{{GCFLAGS}}" -o {{BIN}} {{ENTRY}}

run: build
    ./{{BIN}}

lint:
    golangci-lint run ./...
