default: dev

VERSION := "1.0.0"
BUILDTIME := `date -u '+%Y-%m-%d_%H:%M:%S'`
LDFLAGS := "-s -w -X main.Version=" + VERSION + " -X main.BuildTime=" + BUILDTIME
GCFLAGS := "all=-B"
BIN := "spider"
ENTRY := "./cmd/spider/main.go"

dev:
    go run {{ENTRY}}

build:
    go build \
      -ldflags={{LDFLAGS}} \
      -gcflags={{GCFLAGS}} \
      -o {{BIN}} \
      {{ENTRY}}

build-pgo:
    go build \
      -pgo=default.pgo \
      -ldflags={{LDFLAGS}} \
      -gcflags={{GCFLAGS}} \
      -o {{BIN}} \
      {{ENTRY}}

run: build
    ./{{BIN}}

lint:
    golangci-lint run ./...
